import type { Metadata } from "next";
import { Caesar_Dressing, Tillana, Nunito_Sans } from "next/font/google";
import { ThemeProvider as NextJSThemeProvider } from "next-themes";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Scroller from "@/components/scroller";

const caesarDressing = Caesar_Dressing({
  variable: "--font-caesarDressing",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const tillana = Tillana({
  variable: "--font-tillana",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], 
  display: "swap",
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunitoSans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "800", "900"], 
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wordsmith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${caesarDressing.variable} ${tillana.variable} ${nunitoSans.variable} antialiased`}
      >
        <NextJSThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Header />
          <main className="min-h-screen container mx-auto max-w-7xl px-4 py-8 lg:pt-18">
            {children}
          </main>
          <Footer />
          <Scroller />
        </NextJSThemeProvider>
      </body>
    </html>
  );
}
